common: &common
  github:
    user:
    password:
    token:
    repos:
      - name:
        job:
    organization:

  jenkins:
    base_url:


development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
